model:
  name: "MedViT"
  params:
    depths: [3, 4, 3, 2]
    num_heads: 32
    drop_rate: 0.1
    num_classes: 101
    stem_chs: [64, 32, 64]
    pretrained: False

optimizer:
  name: "AdamW"
  params:
    lr: 0.00001
    weight_decay: 0.001

training:
  num_epochs: 10
  loss: "cross entropy"

dataset:
  name: "FOOD101"
  img_size: (3, 224, 224)
  num_classes: 101
