model:
  name: "testion"
  params:
    depth: [4, 2, 2]
    num_heads: 4
    mlp_ratio: 4.0
    drop_rate: 0.1
    num_classes: 10
    head_bias: False
    patch_embedding:
      type: "EarlyConv"
      params:
        in_channels: 3
        embed_dim: 64
        patch_size: 2
        out_channels: 128
    positional_encoding:
      type: "Fixed2DPositionalEmbedding"
      params:
        additive: True
        img_size: (224, 224)
        requires_grad: True
        #todo Hacer que IMG_size de dataset y positional calzen

optimizer:
  name: "AdamW"
  params:
    lr: 0.001
    weight_decay: 0.01

training:
  num_epochs: 5
  loss: "cross entropy"

dataset:
  name: "FOOD101"
  img_size: (3, 224, 224)
  num_classes: 10
