model:
  name: "testion"
  params:
    depth: [7, 2, 2]
    num_heads: 4
    mlp_ratio: 4.0
    drop_rate: 0.1
    num_classes: 101
    head_bias: False

optimizer:
  name: "AdamW"
  params:
    lr: 0.0005
    weight_decay: 0.01

training:
  num_epochs: 10
  loss: "cross entropy"

dataset:
  name: "FOOD101"
  img_size: (3, 224, 224)
  num_classes: 101
